name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org
          pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

      # Code Quality Analysis with SonarQube
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          projectBaseDir: ./src
          args: |
            -Dsonar.projectKey=my_project
            -Dsonar.organization=my_org
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

      # Security Scan with Trivy
      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: 1
          format: table

      # Linting with flake8
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      # Run Unit Tests
      - name: Run unit tests with pytests
        run: |
          pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing

      # Code Coverage Analysis (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # Optional: Separate Security Job
  security_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: 1
          format: table
